---
- hosts: "nginx"
  become: true
  tasks:
  - name: Install tuned
    package:
      name: tuned
      state: present
  - name: Starting tuned
    systemd: started
      name: tuned
      enabled: true
      masked: no
