---
- hosts: "nginx"
  become: true
  tasks:
  - name: Install tuned
    package:
      name: tuned
      state: present
  - name: Starting tuned
    systemd: 
      name: tuned
      state: tarted
      enable: true
      masked: no
